In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nolasthitnotomorrow/radioml2016-deepsigcom")

print("Path to dataset files:", path)

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("marwanabudeeb/rml201610b")

print("Path to dataset files:", path)

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("pinxau1000/radioml2018")

print("Path to dataset files:", path)

In [1]:
import h5py

f = h5py.File("dataset/2/GOLD_XYZ_OSC.0001_1024.hdf5", "r")

In [2]:
f.keys()

<KeysViewHDF5 ['X', 'Y', 'Z']>

In [3]:
f["X"].shape

(2555904, 1024, 2)

In [4]:
f["Y"].shape

(2555904, 24)

In [5]:
f["Y"][780022]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [12]:
import numpy as np

In [13]:
y_1d = np.argmax(f["Y"], axis=1)

In [17]:
y_1d[890000:890005]

array([8, 8, 8, 8, 8])

In [18]:
f["Z"].shape

(2555904, 1)

In [21]:
f["Z"][:10]

array([[-20],
       [-20],
       [-20],
       [-20],
       [-20],
       [-20],
       [-20],
       [-20],
       [-20],
       [-20]])

In [ ]:
mods, snrs = [sorted(list(set([k[j] for k in Xd.keys()]))) for j in [0, 1]]

In [ ]:
mods

In [24]:
# 步骤1：定义要提取的单个目标值
target = -20

# 步骤2：提取索引（关键：arr.flatten()将(2555904,1)展平为(2555904,)，避免维度问题）
idx_single = np.where(np.array(f["Z"]).flatten() == target)[0]

# 查看结果
print(f"数值{target}的所有索引：", idx_single)
# 测试小例子输出：数值-18的所有索引： [1 6]，与测试数组一致，正确！

数值-20的所有索引： [      0       1       2 ... 2453501 2453502 2453503]


In [25]:
2555904 - 2453503

102401

In [27]:
len(idx_single)

98304

In [28]:
4096 * 24

98304

In [29]:
len(
    [
        "OOK",
        "4ASK",
        "8ASK",
        "BPSK",
        "QPSK",
        "8PSK",
        "16PSK",
        "32PSK",
        "16APSK",
        "32APSK",
        "64APSK",
        "128APSK",
        "16QAM",
        "32QAM",
        "64QAM",
        "128QAM",
        "256QAM",
        "AM-SSB-WC",
        "AM-SSB-SC",
        "AM-DSB-WC",
        "AM-DSB-SC",
        "FM",
        "GMSK",
        "OQPSK",
    ]
)

24

In [30]:
np.count(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

AttributeError: module 'numpy' has no attribute 'count'

In [31]:
l = []

for i in f["Z"]:
    if i not in l:
        l.append(i)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/wwx_amc/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3701, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_4141442/1211562009.py", line None, in <module>
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/wwx_amc/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2201, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/wwx_amc/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1193, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/wwx_amc/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1064, in structured_traceback
    ret

In [32]:
l

[array([-20]),
 array([-18]),
 array([-16]),
 array([-14]),
 array([-12]),
 array([-10]),
 array([-8]),
 array([-6]),
 array([-4]),
 array([-2]),
 array([0]),
 array([2]),
 array([4]),
 array([6]),
 array([8]),
 array([10]),
 array([12]),
 array([14]),
 array([16]),
 array([18]),
 array([20]),
 array([22]),
 array([24]),
 array([26]),
 array([28]),
 array([30])]